services:
  mysql:
    image: 'mysql:8.4.5'
    container_name: mysql-8.4.5
    environment:
      - MYSQL_DATABASE=bookstore
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=user
    ports:
      - '3306:3306'
    labels:
      org.springframework.boot.jdbc.parameters: 'serverTimezone=UTC'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
    name: bookstore_vol
