services:
  mysql:
    image: 'mysql:8.0.35'
    environment:
      - 'MYSQL_DATABASE=bookstore'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3305:3306'
